### ISSUE TITLE
在拖动调整大小时宽高会出现小数

### ISSUE THREAD

**Issue by Mayyuji** [gausszhou/vue3-drag-resize-rotate#11]
### 在拖动和调整区域的大小时宽高会出现超长小数位
- 拖动边界调整宽高会出现下图这种情况
- <img width="400px" src="https://github.com/gausszhou/vue3-drag-resize-rotate/assets/67718546/4e260aa1-db6f-4d11-bb04-d80adee3462e"/>
感觉缓慢拖动的时候触发概率可能会高一些
### 复现
使用官网示例中的 事件(新增)-> 调整大小事件

**Comment by gausszhou** [comment]
是的，目前是没限制数字的精度
