### ISSUE TITLE
为什么我设置了:parent="true"后 只是限制了中心点不能出父级？

### ISSUE THREAD

**Issue by wzs28150** [gausszhou/vue3-drag-resize-rotate#13]
![image](https://github.com/gausszhou/vue3-drag-resize-rotate/assets/21290257/1a6703ac-096e-4dd8-af4f-e85d1858a451)
拖拽的元素有一半是可以出去的，  拖到一半时就不能再往外拖动了

**Comment by gausszhou** [comment]
> 当我设置了rotatable旋转的时候会 限制只能以拖拽的元素的中心点限制

是的，目前是这样设计的，后面可以考虑改成包围盒限制
