### ISSUE TITLE
在初次渲染组件时，增加位置与边界的判断

### ISSUE THREAD

**Issue by Danjuanlab** [gausszhou/vue3-drag-resize-rotate#18]
当使用这个库为移动端写框架布局时，假设一开始是为ipad做的位置和长宽，然后后来又有一个连接来自手机，那么此时加载框架时，内部的元素就可能超过页面边界。因为一开始渲染的时候并没有做边界碰撞的判断。这个可以优化下
![image](https://github.com/gausszhou/vue3-drag-resize-rotate/assets/42509669/cccaaca8-4b2b-4093-9df4-d0c9eda7f87b)

**Comment by gausszhou** [comment]
#29
