### ISSUE TITLE
旋转角度事件（新增）  样例失败

### ISSUE THREAD

**Issue by duzc2** [gausszhou/vue3-drag-resize-rotate#22]
调整旋转角度触发事件rotating和rotatestop 样例中，rotating 没有 发生变化。
旋转时组件上没有显示出 "你正在旋转" 

https://gausszhou.github.io/vue3-drag-resize-rotate/#/events/events-rotating

我自己测试的时候 onRotating 有效
onRotateStop 没有被执行。

**Comment by duzc2** [comment]
哦。我自己的测试没问题。我的stop大写了，所以没有回调。

**Comment by gausszhou** [comment]
好的
