### ISSUE TITLE
无法激活组件

### ISSUE THREAD

**Issue by wenbinwumei** [gausszhou/vue3-drag-resize-rotate#26]
当设置仅窗口标题栏可以拖动时，就无法点击窗体激活组件，只能点击标题栏激活，如何设置？
个人感觉组件激活与否与拖拽应当分开，我是在做多窗口功能时发现的，需要点击B窗体的时候，A窗体自动触发失活事件，但仅能通过标题栏拖动窗体，拜托，看到赶紧回复

**Comment by gausszhou** [comment]
#30
