### ISSUE TITLE
vue3 use import error

### ISSUE THREAD

**Issue by Canees** [gausszhou/vue3-drag-resize-rotate#3]
GlobalVue.use is not a function
![image](https://user-images.githubusercontent.com/40012261/224590388-4816eef3-88af-4955-a233-370550145237.png)

**Comment by Canees** [comment]
> GlobalVue.use is not a function ![image](https://user-images.githubusercontent.com/40012261/224590388-4816eef3-88af-4955-a233-370550145237.png)

![image](https://user-images.githubusercontent.com/40012261/224647098-0f00c152-009b-46fb-89fa-d999af01123c.png)

**Comment by gausszhou** [comment]
thanks
