### ISSUE TITLE
[BUG] 我在升级了3.0.2版本后，准备测试激活的相关问题，但是在原3.0.1下可以正常的使用，但3.0.2直接报错

### ISSUE THREAD

**Issue by wenbinwumei** [gausszhou/vue3-drag-resize-rotate#32]
![image](https://github.com/gausszhou/vue3-drag-resize-rotate/assets/22092821/9b3dbd50-029c-4a62-9287-629cbaf7420f)
我不知道哪里出了问题 还是3.0.2的使用方式发生了变化

**Comment by gausszhou** [comment]
https://github.com/vuejs/core/issues/4344

**Comment by wenbinwumei** [comment]
非常感谢，已经不报错了，按照你给的提示，我在webpack配置中加入
`chainWebpack (chain) {
        chain.resolve.symlinks(false)
        chain.resolve.alias.set( 'vue', path.resolve('./node_modules/vue'))
      }`就可以了
