### ISSUE TITLE
Types and docs-translation

### ISSUE THREAD

**Issue by S1ngularity96** [gausszhou/vue3-drag-resize-rotate#9]
Hello Sir,

first of all, I want to say that this is a very good project and like the Vue component. I would like, to make the library more accessible to the general public, by translating the documentation into English. One possibility is to add a button that switches between the languages. 

Also, I noticed that there are currently no types for Typescript.

I would like to contribute by providing translations for English and adding the types. I just need an okay from the maintainer, so that the changes will be applied after consultation and review.

**Comment by S1ngularity96** [comment]
Great. Thats good to hear. I'll start with the translations and then add the types.

**Comment by S1ngularity96** [comment]
@gausszhou I have started to work on the task. When installing the NPM packages I had noticed that very many packages were outdated. I also noticed that the project is still implemented with rollup and webpack, which is noticeable during development by slow loading times. Therefore I updated the most important packages and replaced Rollup with Vite. 

In the next step I had a closer look at how the translation problem can be solved. I noticed that the Markdown files and the Vue files are merged and the corresponding routes are generated. I had my difficulties to work with vueI18n and didn't see a good way to translate the Markdown files and the Vue files. In the Vue SF components, for example, you also have many comments. Unfortunately these can't be translated, because the text of the file is just copied. 

I had the idea to document the library with [VitePress](https://vitepress.dev/). Out-of-the-box everything worked exactly as I imagined. On top is the Markdown text and underneath the example code highlighted in a box. 

I now have to make decisions with you.
a) is it ok to keep the project migrated to Vite?
b) should we move the documentation to a separate repository and implement further translations in the form of a fork like vue does? Look at the examples [Vue translations](https://github.com/vuejs-translations)

With regards

**Comment by S1ngularity96** [comment]
@gausszhou , would you like to leave a short answer please?

**Comment by gausszhou** [comment]
@S1ngularity96 

Sorry, I just noticed your message
1. Yes we can migrate to vite for packaging
2. Comments should be in English
3. vitepress is good. But I don't know how to embed the demo example

**Comment by S1ngularity96** [comment]
@gausszhou Check this pull-request for updating to vite. [update/vite-and-dependecies](https://github.com/gausszhou/vue3-drag-resize-rotate/pull/10)

**Comment by S1ngularity96** [comment]
I'm finished with the VitePress Docs. Everything looks nice so far. I encountered an error during docs build. Your latest release builds an esm module but there is no `"type": "module"` in package.json. VitePress needs this setting in your package.json file otherwise the build wont work. 
Could you please add this and re-release your package?

**Comment by S1ngularity96** [comment]
@gausszhou any progress here?
